// <auto-generated />
using System;
using AuthApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthApi.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("AuthApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75e9c81e-2565-42df-b7f6-3032ab3de882"),
                            Email = "admin@pucminas.br",
                            Password = "$2a$11$PiDrdiHh/r6ZLfbKnbI10OHLEI59GZEId9glBxy.SbUMyPmhIKmUq",
                            Role = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("16f907e9-39d4-451c-9399-85f2d01de644"),
                            Email = "jogador@pucminas.br",
                            Password = "$2a$11$FSGN1GPGS5ngbqer7oyD0uagPzhDrzUBNfhgR4WGXZC7X1jgiz4l6",
                            Role = "Jogador"
                        },
                        new
                        {
                            Id = new Guid("0ed9eded-1aa0-44e0-83de-e3c10aebaf83"),
                            Email = "capitao@pucminas.br",
                            Password = "$2a$11$dphfXwxi6e3SpCMuiLYSZuKWiSPMm2P1xDUbteeLgNhCOjGZJ.noK",
                            Role = "Capitao"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
